# server
server:
  port: 10031

# api
api:
  prefix: api
  version: v1

# response filter
response:
  errors:
    hide-detail: false

# eureka client
eureka:
  instance:
    homePageUrl: /swagger-ui.html
    healthCheckUrlPath: /actuator/health
    statusPageUrlPath: /actuator/info
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka

# remote client addition
remote:
  baseURL: https://s.search.bilibili.com
  contextURL: /cate/search