server:
  port: 8080
  servlet:
    context-path: /api

api:
  version: v1

rest:
  connectTimeout: 1000
  readTimeout: 1000

swagger:
  enabled: true
  protocol: http

spring:
  application:
    name: service-common
    description: Common configs and factory for Micro Services

info:
  contact:
    author: Anddd7
    email: liaoad_space@sina.com
    url: https://github.com/Anddd7

response:
  validation: false
  errors:
    hide-detail: true
