server:
  port: 10000
  servlet:
    context-path: /api

api:
  version: v1

remote:
  baseURL: http://localhost:10030
  contextURL: /v1/api

rest:
  connectTimeout: 5000
  readTimeout: 5000

swagger:
  enabled: true
  protocol: http

info:
  app:
    name: Analysis 4 BILIBILI - Analysis Service
    description: MicroService - Analysis 4 BILIBILI - Analysis Service
    protocol: http
  version: 1.0.0
  contact:
    author: Anddd7
    email: liaoad_space@sina.com
    url: https://github.com/Anddd7
