# server
server:
  port: 10043

# api
api:
  prefix: /api
  version: v1

# response filter
response:
  errors:
    hide-detail: false

# eureka client
eureka:
  instance:
    homePageUrl: /swagger-ui.html
    healthCheckUrlPath: /actuator/health
    statusPageUrlPath: /actuator/info
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka

# feign
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

# mongodb & redis
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/bilibili
  redis:
    host: localhost
    port: 6379