# eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:9999/eureka

# mongodb
spring:
  data:
    mongodb:
      uri: mongodb//mongodb:27017/bilibili
  redis:
    host: redis
    port: 6379