# server
server:
  port: 10000

# eureka client
eureka:
  instance:
#    homePageUrl: /swagger-ui.html
#    healthCheckUrlPath: /actuator/health
#    statusPageUrlPath: /actuator/info
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka

# zuul config
zuul:
  routes:
    bilibili-analysis:
      path: /bilibili-analysis/**
      serviceId: bilibili-analysis-api
