# server
server:
  port: 10000

# eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka

# zuul config
zuul:
  host:
    connect-timeout-millis: 10000   # starting the connection
    socket-timeout-millis: 5000     # monitor the continuous incoming data flow
    max-total-connections: 1000
    max-per-route-connections: 100
  routes:
    bilibili-analysis:
      path: /bilibili-analysis/**
      serviceId: bilibili-analysis-api
