# server
server:
  port: 10000

# eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka

# zuul config
zuul:
  routes:
    bilibili-dashboard:
      path: /bilibili/**
      serviceId: bilibili-dashboard

ribbon:
  ReadTimeout: 60000
